version: '3'

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always

  postgres:
    image: postgres:13
    container_name: guacamole_postgres
    restart: always
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ongraph
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: always
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: ongraph
    ports:
      - "8080:8080"
    depends_on:
      - guacd
      - postgres

  ubuntu-lab:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: ubuntu-lab
    restart: unless-stopped
    expose:
      - "22"
    ports:
      - "2222:22"
    environment:
      - ROOT_PASSWORD=root
    command: "/usr/sbin/sshd -D"
    
volumes:
  postgres_data:


